### ISSUE TITLE
Feature request: specify binners to exclude in Recover

### ISSUE THREAD

**Issue by StevenJRobbins** [rhysnewell/flight#15]
Feature request: It would be nice to be able to specify which binners to include/exclude from the `Aviary recover` workflow. For me, Maxbin seems to get stuck on some of my data and takes several days to run. Spread over many samples, that's a lot of time. I think it will finish eventually but since I doubt it will add critical improvement to the final MAGs by itself, it'd be nice to be able to exclude it to save time. I can imagine others may have cases where they'd want to do this, if not just to do a quicker run for testing, so may be worth implementing.

Thanks!

**Comment by rhysnewell** [comment]
This is something I've been meaning to implement, so it's definitely on my radar just haven't had the time to work out a suitable implementation

**Comment by StevenJRobbins** [comment]
I thought that might be the case. Will look forward to it!

**Comment by rhysnewell** [comment]
Also, just realised you opened this on the wrong github page. This is flight, not aviary. I'll close this now, but feel free to open again on aviary

**Comment by StevenJRobbins** [comment]
Ah nuts. My bad. I’ll reopen it as a placeholder.

Steven Robbins, PhD
Postdoctoral researcher
Australian Centre for Ecogenomics
L5/76 MBS Bldg
University of Queensland
http://ecogenomic.org/personnel/dr-steven-robbins


From: Rhys Newell ***@***.***>
Date: Tuesday, 24 May 2022 at 1:59 pm
To: rhysnewell/flight ***@***.***>
Cc: Mr Steven Robbins ***@***.***>, Author ***@***.***>
Subject: Re: [rhysnewell/flight] Feature request: specify binners to exclude in Recover (Issue #15)

Also, just realised you opened this on the wrong github page. This is flight, not aviary. I'll close this now, but feel free to open again on aviary
