### ISSUE TITLE
problem with rosella installation in conda

### ISSUE THREAD

**Issue by jvollme** [rhysnewell/flight#16]
I had a [problem with rosella](https://github.com/rhysnewell/rosella/issues/26) when it tried to run flight, as it could not import skbio. I thought the problem was with the conda recipe, but it turns out it still doesn't work in conda environments that clearly have scikit-bio installed.

Turns out that the main script of flight uses ```#!/usr/bin/python3``` as a shebang, thereby simply ignoring the conda environment alltogether.
This needs to be changed to ```#!/usr/bin/env python``` in order to access the python modules of the conda environment

**Comment by rhysnewell** [comment]
Perhaps I'm misinterpreting what you are saying, but all of the main files of flight appear to have the correct shebang: `#!/usr/bin/env python3` e.g. https://github.com/rhysnewell/flight/blob/master/flight/flight.py

Can you point to where you found the incorrect shebang?

**Comment by jvollme** [comment]
oh strange. I found the incorrect shebang in the instance of flight on my system, after installing it with pip from within my conda environment. It seems that pip installed it in a .local/bin/flight folder in my home folder instead of my conda environment that usually should be the default behaviour... And along the process the shebang got changed by pip?

this may be because, even stranger, when creating the enironment for rosella with all the assumed requirements with "conda create -n rosella scikit-bio matplotlib seaborn umap numba rosella", somehow python 2.7 got installed, making it impossible to install flight into that environment. I am now not sure if there is not maybe just something seriously messed up with my conda installation?

Especially since now, (after creating my fourth rosella environment, this time specifically stating ```python=3```) i get a problem that the installed scikit-bio version is not compatible with the installed scipy version:

```
File \"/home/ww5070/.conda/envs/rosella4/lib/python3.10/site-packages/skbio/stats/distance/_mantel.py\", line 16, in <module>
from scipy.stats import PearsonRConstantInputWarning\nImportError: cannot import name 'PearsonRConstantInputWarning' from 'scipy.stats' (/home/ww5070/.conda/envs/rosella4/lib/python3.10/site-packages/scipy/stats/__init__.py)"
```

**Comment by rhysnewell** [comment]
Yeah, seems like something truly bizarre is happening with your conda. Have you checked that your .condarc is set up correctly and you've got your channels configured correctly?

**Comment by jvollme** [comment]
.condarc looks ok and although i have added bioconda to my channel list, I have the channel-priority set so that python packages are preferrably installed from conda-forge rather than bioconda, if they exist in both (which is the recommenden channel-priority according to the miniconda and the bioconda documantation). I never had this problem before...

However it seems after some googling, that some versions of skBio not working together with the newest versions of scipy is a r[elatively common problem](https://github.com/biocore/scikit-bio/issues/1818)... Just for testing, could you tell me which specific scipy and scikit-bio versions you are using successfully with rosella & flight?

**Comment by jvollme** [comment]
ok now it works. The python version problem was something to do with my conda setup. But with the current scikit-bio version scipy must be older than >1.9. So during intallation scipy=1.8.1 needs to be specified, currently
